# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "topLog Log Blog"
description: > # this means to ignore newlines until "email:"
   TopLog's Blog about Logs

name: "topLog Inc"
author: "topLog Inc"
email: team@toplog.io
#blog logo
logo: "/assets/images/log-justlogs.png"
# blog cover
cover: "/assets/images/wood-bg.png"

paginate:	5

analytics :
  provider : google
  google :
      tracking_id : 'UA-56068240-1'

url: "http://toplog.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/logdrivers
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/toplog
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:


authors:
  # matt:
  #   display_name: Matt Hackett
  #   gravatar: 60fd5218fff6927c0ed376cce01c5460
  #   email: matt@lostdecadegames.com
  #   web: http://www.richtaur.com/
  #   twitter: richtaur
  #   github: richtaur
  # geoff:
  #   display_name: Geoff Blair
  #   gravatar: 76dbcc74021b8039f14c7b583978b56d
  #   email: geoff@lostdecadegames.com
  #   web: http://www.geoffblair.com/
  #   twitter: geoffblair
  #   github: geoffb
  patrick:
    display_name: Patrick LaRoche
    email: patrick@toplog.io
    twitter: plaroche
    github: PLaRoche
  yalcin:
    display_name: yalcin
    email: yalcin@toplog.io
